// Typy zařízení

#define dtAllDevices              0x00
#define dtVypinac                 0x01
#define dtRele8                   0x02
#define dtRizeni                  0x03
#define dtStmivac                 0x04
#define dtRizeniRaspberry         0x05
#define dtTabloDuo                0x06
#define dtVeronaDuo               0x07
#define dtGSM                     0x08
#define dtTelefon                 0x09
#define dtTablo                   0x0A
#define dtSenzor                  0x0B
#define dtPIR                     0x0C
#define dtOtocny                  0x0D
#define dtKlavesnice              0x0E
#define dtGSM2                    0x0F
#define dtMicTester               0x10
#define dtSirena                  0x11
#define dtInterkom_Tablo4T        0x12
#define dtBrana                   0x13
#define dtKour                    0x14
#define dtInfra                   0x15
#define dtTlacitkoC               0x16
#define dtTeplomer                0x17
#define dtMotorDvere              0x18
#define dtSimplex                 0x19
#define dtMelodyNice              0x1A
#define dtTermoventil             0x1B
#define dtZdrojCasu               0x1C
#define dtTabloML                 0x1D
#define dtOddelovac               0x1E
#define dtZdroj                   0x1F
#define dtVeronaMelody            0x20
#define dtKamera                  0x21
#define dtTablo1M                 0x22
#define dtCidloVetru              0x23
#define dtTelefon3                0x24
#define dtInfoLED                 0x25
#define dtSchranka                0x26
#define dtPS                      0x27
#define dtBudik                   0x28
#define dtTabloRD                 0x29
#define dtDisplejTP               0x2A
#define dtRegTDN                  0x2B
#define dtDochazka                0x2C
#define dtSpinac2RP               0x2D
#define dtSpinacBP                0x2E
#define dtCteckaKU68              0x2F
#define dtVysilacZpravy           0x30
#define dtOsvetleniLED            0x31
#define dtPS2015                  0x32
#define dtTabloDuoPlusV2          0x33
#define dtRTS                     0x34
#define dtDetektorPohybu          0x35
#define dtOpenTherm               0x36
#define dtRozhraniCtecky          0x37
#define dtViolaMelody             0x38
#define dtCteckaMIFARE            0x39
#define dtCteckaBluetooth         0x3A
#define dtRozhraniNanoPI          0x3B
#define dtCteckaRFID              0x3C
#define dtOS4                     0x3D
#define dtSud                     0x3E
#define dtWH1080                  0x3F
#define dtServerEINK              0x40
#define dtTabloMelodyFL           0x41
#define dtRozhraniRS485           0x42
#define dtPV6                     0x43
#define dtCteckaRFIDFL            0x44
#define dtCteckaMifareFL          0x45
#define dtVeronaDuoPlus           0x46    // Verze 2023
#define dtViolaDuoPlus            0x47    // Verze 2023
#define dtVivaHF50                0x48
#define dtPS3                     0x49
#define dtVivaHF35                0x4A
#define dtJednotkaVstupu          0x4B
#define dtTlacitkoDuoPlus         0x4C
#define dtGSM3                    0x4D
#define dtTabloDuoPlusFL          0x4E
#define dtKlimatizaceSamsung      0x4F
#define dtKonfigurator            0x0100

#define ID_Rizeni                 1

